title: Danny Pressler # your name (or website title) here
logo: "/images/head Shot.jpeg?raw=True" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Edit these links below   
  <br>
  in _config.yml 
  <br><br>
  <a href="https://www.linkedin.com/in/danny-pressler/">LinkedIn</a> 
  <br>
  <a href="https://docs.google.com/document/d/1OZFo_MYryiSrIePP2O6gl_asl9wdEXH1Pt8VXrazSj0/edit" class="btn btn--info">Resume</a>  
  <br>
  <a href="https://bowen.finance/" class="btn btn--info">Portfolio</a>  
  <br>
  <a href="https://github.com/DannyPress">GitHub</a>  
  <br>
  
theme: jekyll-theme-minimal
